version: "3.1"
services:
  suevey-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    networks:
      - survey-net
    restart: unless-stopped
    depends_on:
      - survey-mongo
    command: npm run dev

  survey-mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - survey-net
    restart: always
    volumes:
      - database_vol:/data/db

networks:
  survey-net:
    driver: bridge

volumes:
  database_vol:
